# Generated by Django 3.0.4 on 2020-03-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20200313_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(default='images/default/default_beer.png', upload_to='images/'),
        ),
    ]
