# Generated by Django 3.0.4 on 2020-03-19 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0001_initial'),
        ('beers', '0004_auto_20200319_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brewered', to='breweries.Brewery'),
        ),
        migrations.DeleteModel(
            name='Brewery',
        ),
    ]
