# Generated by Django 3.0.4 on 2020-03-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_auto_20200320_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='icon',
            field=models.ImageField(default='images/default/default_beer.png', null=True, upload_to='images/'),
        ),
    ]
