# Generated by Django 3.0.4 on 2020-03-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0001_initial'),
        ('beers', '0006_auto_20200324_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='hops',
            field=models.ManyToManyField(blank=True, related_name='used_hops', to='hops.Hop'),
        ),
    ]
