# Generated by Django 3.0.4 on 2020-03-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0007_auto_20200324_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hop',
        ),
    ]
