# Generated by Django 3.0.4 on 2020-03-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0009_auto_20200324_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='title',
            field=models.CharField(db_index=True, max_length=140),
        ),
    ]
