# Generated by Django 3.0.4 on 2020-04-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0016_auto_20200413_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
