# Generated by Django 3.0.4 on 2020-04-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0017_beer_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='date_pub',
            field=models.DateTimeField(null=True),
        ),
    ]
