# Generated by Django 3.0.4 on 2020-04-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0018_auto_20200416_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
