# Generated by Django 3.0.4 on 2020-04-15 23:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beers', '0019_auto_20200416_0119'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beer',
            unique_together={('title', 'version', 'hunter')},
        ),
    ]
