# Generated by Django 3.0.4 on 2020-04-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0007_brewery_country'),
        ('beers', '0020_auto_20200416_0211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beer',
            unique_together={('title', 'version', 'brewery')},
        ),
    ]
