# Generated by Django 3.0.4 on 2020-04-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0007_brewery_country'),
        ('beers', '0021_auto_20200416_1426'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beer',
            unique_together={('title', 'version', 'brewery_id')},
        ),
    ]
