# Generated by Django 3.0.4 on 2020-04-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0022_auto_20200416_1523'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='beer',
            constraint=models.UniqueConstraint(fields=('title', 'version', 'brewery'), name='beer_constraint'),
        ),
    ]
