# Generated by Django 3.0.4 on 2020-04-20 19:52

import beers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0024_beer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='title',
            field=models.CharField(db_index=True, max_length=140, validators=[beers.models.validate_title]),
        ),
    ]
