# Generated by Django 3.0.4 on 2020-05-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0028_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='BeerComment',
        ),
    ]
