# Generated by Django 3.0.4 on 2020-05-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0031_beercomment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='icon',
        ),
    ]
