# Generated by Django 3.0.4 on 2020-05-17 14:43

import beers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0032_remove_beer_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, default='images/default/default_beer.png', null=True, upload_to=beers.models.beer_directory_path_with_uuid),
        ),
    ]
