# Generated by Django 3.0.4 on 2020-05-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0033_auto_20200517_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, editable=False, max_length=200),
        ),
    ]
