# Generated by Django 3.0.4 on 2020-06-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0035_auto_20200520_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='votes_total',
        ),
    ]
