# Generated by Django 3.0.4 on 2020-03-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AromaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hop',
            name='aroma_profile',
            field=models.ManyToManyField(blank=True, related_name='aroma_profile', to='hops.AromaProfile'),
        ),
    ]
