# Generated by Django 3.0.4 on 2020-03-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0002_auto_20200324_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aromaprofile',
            options={'ordering': ('title',)},
        ),
    ]
