# Generated by Django 3.0.4 on 2020-04-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0003_auto_20200325_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HopManager',
        ),
    ]
