# Generated by Django 3.0.4 on 2020-05-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
