# Generated by Django 3.0.4 on 2020-04-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0004_brewery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='slug',
            field=models.SlugField(),
        ),
    ]
