# Generated by Django 3.0.4 on 2020-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0005_auto_20200411_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
