# Generated by Django 3.0.4 on 2020-04-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0007_brewery_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BreweryManager',
        ),
    ]
