# Generated by Django 3.0.4 on 2020-05-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0008_delete_brewerymanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
